version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME:-nginx-proxy}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/templates:/etc/nginx/conf.d/templates
    environment:
      - DOMAINS=${DOMAINS}
      - SERVER_IP=${SERVER_IP}
      - NOTIFY_EMAIL=${NOTIFY_EMAIL}
    networks:
      - proxy-network

networks:
  proxy-network:
    name: ${COMPOSE_PROJECT_NAME:-nginx-proxy}_network