version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    container_name: ${COMPOSE_PROJECT_NAME:-nginx-proxy}_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/templates:/etc/nginx/conf.d/templates
      - ./scripts:/scripts
      - certbot-www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    environment:
      - DOMAINS=${DOMAINS}
      - SERVER_IP=${SERVER_IP}
      - NOTIFY_EMAIL=${NOTIFY_EMAIL}
      - ENABLE_SSL=${ENABLE_SSL:-false}
      - EMAIL_FOR_SSL=${EMAIL_FOR_SSL}
      - WILDCARD_LOCALHOST_TARGET=${WILDCARD_LOCALHOST_TARGET} # Включает/выключает wildcard
      - WILDCARD_LOCALHOST_PORTS=${WILDCARD_LOCALHOST_PORTS}   # Определяет порты для поддоменов
    networks:
      - proxy-network

volumes:
  certbot-www:
  letsencrypt:

networks:
  proxy-network:
    name: ${COMPOSE_PROJECT_NAME:-nginx-proxy}_network