name: Deploy Nginx Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set permissions for scripts
        run: |
          chmod +x scripts/deploy.sh
          ls -la scripts/
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          echo "Creating archive..."
          # Создаем архив проекта
          tar -czf nginx-proxy.tar.gz \
            --warning=no-file-changed \
            --exclude='./.git' \
            --exclude='./.github' \
            --exclude='./certbot' \
            --exclude='./.cursor' \
            .
          
          echo "Copying archive to server..."
          # Копируем архив на сервер с подробным выводом
          scp -v nginx-proxy.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/tmp/
          
          echo "Deploying on server..."
          # Выполняем деплой на сервере с дополнительными проверками
          ssh -v ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            echo 'Creating directory...';
            mkdir -p ~/nginx-proxy;
            
            echo 'Extracting archive...';
            tar -xzf /tmp/nginx-proxy.tar.gz -C ~/nginx-proxy;
            
            echo 'Checking files...';
            ls -la ~/nginx-proxy;
            ls -la ~/nginx-proxy/scripts;
            
            echo 'Setting permissions...';
            chmod +x ~/nginx-proxy/scripts/deploy.sh;
            
            echo 'Setting environment...';
            cd ~/nginx-proxy;
            export DOMAINS='${{ secrets.DOMAINS }}';
            export SERVER_IP='${{ secrets.SERVER_IP }}';
            export ENABLE_SSL='${{ secrets.ENABLE_SSL }}';
            export EMAIL_FOR_SSL='${{ secrets.EMAIL_FOR_SSL }}';
            export NOTIFY_EMAIL='${{ secrets.NOTIFY_EMAIL }}';
            export COMPOSE_PROJECT_NAME='nginx-proxy';
            
            echo 'Checking Docker installation...';
            which docker || echo 'Docker not found!';
            which docker-compose || echo 'Docker-compose not found!';
            
            echo 'Running deployment script...';
            bash -x ./scripts/deploy.sh;
          "
      
      - name: Clean up
        if: always()  # Выполнять даже при ошибке
        run: |
          rm ~/.ssh/id_rsa 